zn "%SYS" 
do ##class(Security.Users).UnExpireUserPasswords("*")

// install zpm    
do ##class(Security.SSLConfigs).Create("z")
set r=##class(%Net.HttpRequest).%New(),r.Server="pm.community.intersystems.com",r.SSLConfiguration="z"
do r.Get("/packages/zpm/0.9.0/installer"),$system.OBJ.LoadStream(r.HttpResponse.Data,"c")
zpm
enable -map -globally
exit

zn "USER"
zpm "load /opt/irisbuild":1:1